/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libmansys;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static libmansys.javaconnect.conn;

/**
 *
 * @author HP
 */
public class Bookdetail extends javax.swing.JPanel {

    ResultSet rs;
    Connection conn;
    PreparedStatement pst;

    public Bookdetail() {
        initComponents();
        conn = javaconnect.connectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtisbn = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtauthor = new javax.swing.JTextField();
        txtedition = new javax.swing.JTextField();
        txtpublisher = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnDlt = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 0, 0));
        setPreferredSize(new java.awt.Dimension(1270, 610));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("ISBN Number");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 140, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Book Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Author");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Edition");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Publisher");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        txtisbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtisbnMouseClicked(evt);
            }
        });
        add(txtisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 320, 30));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 320, 30));
        add(txtauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 320, 30));
        add(txtedition, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 320, 30));
        add(txtpublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 320, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("ADD BOOK");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("VIEW BOOK");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("DELETE BOOK");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, -1, -1));

        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/BUTTON.png"))); // NOI18N
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 150, 50));

        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/BUTTON.png"))); // NOI18N
        btnView.setText(" ");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 150, 40));

        btnDlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/BUTTON.png"))); // NOI18N
        btnDlt.setText(" ");
        btnDlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDltActionPerformed(evt);
            }
        });
        add(btnDlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        if (!"".equals(txtisbn.getText()) && !"".equals(txtname.getText()) && !"".equals(txtauthor.getText()) && !"".equals(txtedition.getText()) && !"".equals(txtedition.getText())) {
            String sql = "insert into bookdetails(isbn,name,author,edition,publisher) values(?,?,?,?,?)";

            try {
                pst = conn.prepareStatement(sql);

                pst.setString(1, txtisbn.getText());
                pst.setString(2, txtname.getText());
                pst.setString(3, txtauthor.getText());
                pst.setString(4, txtedition.getText());
                pst.setString(5, txtpublisher.getText());

                pst.execute();

                JOptionPane.showMessageDialog(null, "book added Successfully");

                txtisbn.setText("");
                txtname.setText("");
                txtauthor.setText("");
                txtedition.setText("");
                txtpublisher.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "please fill all the text fields");
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        try {
            String lib = "Select * from bookdetails where  isbn=?";

            pst = conn.prepareStatement(lib);
            pst.setString(1, txtisbn.getText());
            rs = pst.executeQuery();
            if (rs.next()) {

                txtname.setText(rs.getString("name"));
                txtauthor.setText(rs.getString("author"));
                txtedition.setText(rs.getString("edition"));
                txtpublisher.setText(rs.getString("publisher"));

            } else {
                JOptionPane.showMessageDialog(null, "no data for this id");
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDltActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "delete from bookdetails where isbn ='" + txtisbn.getText() + "'";
            PreparedStatement pst1 = conn.prepareStatement(sql);
            pst1.execute();
            JOptionPane.showMessageDialog(this, "Successfully Removed the Record");
        } catch (Exception ex) {
            System.out.println(ex);
        }
        txtisbn.setText("");
        txtname.setText("");
        txtauthor.setText("");
        txtedition.setText("");
        txtpublisher.setText("");
    }//GEN-LAST:event_btnDltActionPerformed

    private void txtisbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtisbnMouseClicked
        // TODO add your handling code here:
        txtisbn.setText("");
        txtname.setText("");
        txtauthor.setText("");
        txtedition.setText("");
        txtpublisher.setText("");
    }//GEN-LAST:event_txtisbnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDlt;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnadd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtauthor;
    private javax.swing.JTextField txtedition;
    private javax.swing.JTextField txtisbn;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpublisher;
    // End of variables declaration//GEN-END:variables
}
