/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libmansys;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;

/**
 *
 * @author HP
 */
public class BorrowingDetails extends javax.swing.JPanel {

    /**
     * Creates new form BorrowingDetails
     */
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    String s;
    ResultSet rs1;

    public BorrowingDetails() {
        initComponents();
        conn = javaconnect.connectDb();
    }

    public void DueDate() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate localDate1 = LocalDate.now().plusDays(14);
        txtDuedate.setText("" + localDate1);
        //System.out.println(dtf.format(localDate)); //2016/11/16
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnsearch = new javax.swing.JButton();
        txtIsbn = new javax.swing.JTextField();
        txtStudentid = new javax.swing.JTextField();
        txtBname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAvailability = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        btnIssue = new javax.swing.JButton();
        txtDuedate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDuedate1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1023, 551));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Icon 1/search.png"))); // NOI18N
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 50, 30));

        txtIsbn.setBorder(new javax.swing.border.MatteBorder(null));
        txtIsbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIsbnMouseClicked(evt);
            }
        });
        txtIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIsbnActionPerformed(evt);
            }
        });
        txtIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIsbnKeyPressed(evt);
            }
        });
        jPanel1.add(txtIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 400, 30));

        txtStudentid.setBorder(new javax.swing.border.MatteBorder(null));
        txtStudentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentidActionPerformed(evt);
            }
        });
        jPanel1.add(txtStudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 400, 30));

        txtBname.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(txtBname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 400, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Due Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ISBN NO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Issued Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 30));

        txtAvailability.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtAvailability.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAvailability.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(txtAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 400, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setText("Return");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel8.setText("Issue");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, -1, -1));

        btnReturn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/BUTTON.png"))); // NOI18N
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 160, 40));

        btnIssue.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnIssue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/BUTTON.png"))); // NOI18N
        btnIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueActionPerformed(evt);
            }
        });
        jPanel1.add(btnIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 160, 40));

        txtDuedate.setBorder(new javax.swing.border.MatteBorder(null));
        txtDuedate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDuedateMouseClicked(evt);
            }
        });
        jPanel1.add(txtDuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 400, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Availability");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, 30));

        txtDuedate1.setBorder(new javax.swing.border.MatteBorder(null));
        txtDuedate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDuedate1MouseClicked(evt);
            }
        });
        jPanel1.add(txtDuedate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 400, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void txtIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsbnActionPerformed

    private void txtStudentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentidActionPerformed

    private void btnIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueActionPerformed
        // TODO add your handling code here:
        String sql = "insert into issuedbooks(isbn,Book_name,st_id,i_date,D_date) values(?,?,?,?,?)";

        try {

            pst = conn.prepareStatement(sql);
            pst.setString(1, txtIsbn.getText());
            pst.setString(2, txtBname.getText());
            pst.setString(3, txtStudentid.getText());
            pst.setString(4, txtDuedate1.getText());
            pst.setString(5, txtDuedate.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "book issued Successfully  ");

            txtIsbn.setText("");
            txtBname.setText("");
            txtStudentid.setText("");
            txtDuedate.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnIssueActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        try {

            String sql1 = "delete from issuedbooks where isbn ='" + txtIsbn.getText() + "'";
            PreparedStatement pst1 = conn.prepareStatement(sql1);
            pst1.execute();
            JOptionPane.showMessageDialog(this, "Successfully Returned the book");
        } catch (Exception ex) {
            System.out.println(ex);
        }

        txtIsbn.setText("");
        txtBname.setText("");
    }//GEN-LAST:event_btnReturnActionPerformed

    private void txtIsbnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIsbnKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtIsbnKeyPressed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        try {
            String lib1 = "Select name from bookdetails where  isbn=?";
            String lib2 = "Select Book_name from issuedbooks where  isbn=?";
            pst = conn.prepareStatement(lib1);
            PreparedStatement pst1 = conn.prepareStatement(lib2);
            pst.setString(1, txtIsbn.getText());
            pst1.setString(1, txtIsbn.getText());
            rs = pst.executeQuery();
            rs1 = pst1.executeQuery();
            if (rs1.next()) {
                JOptionPane.showMessageDialog(null, "sorry book is already issued");
                txtAvailability.setText("UNAVAILABLE");
                btnIssue.setEnabled(false);
            } else {

                if (rs.next()) {
                    txtBname.setText(rs.getString("name"));
                    btnIssue.setEnabled(true);
                    txtAvailability.setText("AVAILABLE");
                } else {
                    JOptionPane.showMessageDialog(null, "sorry there isn't a book called" + txtIsbn.getText());
                }
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void txtIsbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIsbnMouseClicked
        // TODO add your handling code here:
        btnIssue.setEnabled(true);
        txtAvailability.setText("");
    }//GEN-LAST:event_txtIsbnMouseClicked

    private void txtDuedateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDuedateMouseClicked
        // TODO add your handling code here:
        DueDate();
    }//GEN-LAST:event_txtDuedateMouseClicked

    private void txtDuedate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDuedate1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuedate1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIssue;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtBname;
    private javax.swing.JTextField txtDuedate;
    private javax.swing.JTextField txtDuedate1;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtStudentid;
    // End of variables declaration//GEN-END:variables
}
